# dependabot.yaml 是一个固定位置，必须是该目录下，固定名字的文件

version: 2
updates:
# 有 npm maven
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 20
    # Ignore major version updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "US/Eastern"
